class Map():
    vc_xpath = {'search_results':'//*[@id="ApprNotifications_body"]/div[5]/table/tbody/tr[2]/td/div/form/table/tbody/tr[2]/td/table/tbody/tr/td/div[2]/table',
                'summary_button': '//*[@id="PhoenixNavLink_PHX_NAV_SupplierProfile_SupplierSummary"]',
                'summary_page_body': '//*[@id="SupplierSummary_body"]',
                'first_item' : '//*[@id="ApprNotifications_body"]/div[5]/table/tbody/tr[2]/td/div/form/table/tbody/tr[2]/td/table/tbody/tr/td/div[2]/table/tbody/tr[1]/td[1]/a',
                'remove_button': '/html/body/div[5]/table/tbody/tr[2]/td/div/form/table/tbody/tr[2]/td/table/tbody/tr/td/div[2]/table/tbody/tr[1]/td[3]/input',
                'login_button': '/html/body/div/div/div[2]/div[1]/div[3]/form/div/div[3]/div/button'}

    rk_xpath = {'password_box':'//*[@id="password"]',
                'login_button' : '//*[@id="Login"]',
                'search_button': '/html/body/div[4]/div[1]/section/header/div[2]/div[2]/div/button',
                'search_bar': '/html/body/div[4]/div[2]/div[1]/div/div[1]/div/div[1]/lightning-input/div/input',
                'search_result_first' : '//*[@id="brandBand_2"]/div/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div[1]/div[2]/div/div/div/div[2]/div[2]/div[1]/div/div/table/tbody/tr/th/span/a',
                'edit_button': '/html/body/div[4]/div[1]/section/div[1]/div[2]/div[2]/div[1]/div/div/div/div/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-vendor_-record_-page___-vendor__c___-v-i-e-w/forcegenerated-flexipage_vendor_record_page_vendor__c__view_js/record_flexipage-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div[2]/div[1]/slot/flexipage-component2[1]/slot/flexipage-tabset2/div/lightning-tabset/div/slot/slot/flexipage-tab2[1]/slot/flexipage-component2/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_vendor__c___012f1000000n7uaaaq___full___view___recordlayout2/records-record-layout-block/slot/records-record-layout-section[1]/div/div/div/slot/records-record-layout-row[1]/slot/records-record-layout-item[1]/div/div/div[2]/button',
                'supplier_id_box': '/html/body/div[4]/div[1]/section/div[1]/div[2]/div[2]/div[1]/div/div/div/div/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-vendor_-record_-page___-vendor__c___-v-i-e-w/forcegenerated-flexipage_vendor_record_page_vendor__c__view_js/record_flexipage-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div[2]/div[1]/slot/flexipage-component2[1]/slot/flexipage-tabset2/div/lightning-tabset/div/slot/slot/flexipage-tab2[1]/slot/flexipage-component2/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_vendor__c___012f1000000n7uaaaq___full___view___recordlayout2/records-record-layout-block/slot/records-record-layout-section[1]/div/div/div/slot/records-record-layout-row[1]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                'save_button': '/html/body/div[4]/div[1]/section/div[1]/div[2]/div[2]/div[1]/div/div/div/div/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-vendor_-record_-page___-vendor__c___-v-i-e-w/forcegenerated-flexipage_vendor_record_page_vendor__c__view_js/record_flexipage-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div[2]/div[1]/slot/flexipage-component2[1]/slot/flexipage-tabset2/div/lightning-tabset/div/slot/slot/flexipage-tab2[1]/slot/flexipage-component2/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/records-form-footer/div/div/div/runtime_platform_actions-actions-ribbon/ul/li[2]/runtime_platform_actions-action-renderer/runtime_platform_actions-executor-lwc-headless/slot[1]/slot/lightning-button/button',
                'home_button': '/html/body/div[4]/div[1]/section/div[1]/div[1]/one-appnav/div/one-app-nav-bar/nav/div/one-app-nav-bar-item-root[1]/a/span',
                'duplicate_alert': '/html/body/div[4]/div[2]/div'}